/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#001945",
        "surface-container-lowest": "#ffffff",
        "on-background": "#071e27",
        "secondary-fixed-dim": "#bbc8d0",
        "on-primary-fixed-variant": "#00429c",
        "surface": "#f3faff",
        "error": "#ba1a1a",
        "on-secondary-container": "#5a666d",
        "primary-fixed": "#d9e2ff",
        "surface-bright": "#f3faff",
        "error-container": "#ffdad6",
        "secondary-fixed": "#d7e4ec",
        "primary": "#001944",
        "on-primary": "#ffffff",
        "surface-container-low": "#e6f6ff",
        "secondary-container": "#d7e4ec",
        "on-secondary-fixed": "#111d23",
        "surface-container-high": "#d5ecf8",
        "tertiary-fixed": "#8df5e4",
        "on-secondary-fixed-variant": "#3c494f",
        "on-error": "#ffffff",
        "inverse-surface": "#1e333c",
        "tertiary-container": "#003731",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#00201c",
        "surface-dim": "#c7dde9",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#3ba899",
        "surface-tint": "#2b5bb5",
        "on-secondary": "#ffffff",
        "inverse-primary": "#b0c6ff",
        "on-surface": "#071e27",
        "secondary": "#546067",
        "inverse-on-surface": "#dff4ff",
        "surface-container-highest": "#cfe6f2",
        "surface-container": "#dbf1fe",
        "primary-container": "#002c6e",
        "outline-variant": "#c6c5d4",
        "on-primary-container": "#6b95f3",
        "tertiary-fixed-dim": "#70d8c8",
        "on-surface-variant": "#454652",
        "background": "#f3faff",
        "outline": "#767683",
        "surface-variant": "#cfe6f2",
        "tertiary": "#00201c",
        "primary-fixed-dim": "#b0c6ff",
        "on-tertiary-fixed-variant": "#005048",
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      aspectRatio: {
        '4/3': '4 / 3',
        '16/12': '16 / 12',
      },
    },
  },
  plugins: [],
}
